Fixed the unit test and updated the CD workflow

diff --git a/.github/workflows/deployDB.yml b/.github/workflows/deployDB.yml
--- a/.github/workflows/deployDB.yml
+++ b/.github/workflows/deployDB.yml
@@ -8,7 +8,7 @@ on:
       - 'deliverables/yres_scheduler/yres_scheduler_database/yres_schema.sql'
 
 jobs:
-  transfer-and-test:
+  transfer-and-deploy:
     runs-on: ubuntu-latest
 
     steps:
@@ -34,6 +34,30 @@ jobs:
             cd /home/ubuntu/yres/deliverables/yres_scheduler/yres_scheduler_database
             sudo docker-compose down --volumes || true
             sudo docker-compose up -d
+
+      - name: Wait for Deployment to Complete
+        run: sleep 3s
+
+      - name: Test PostgreSQL Connection
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_PRIVATE_KEY }}
+          script: |
+            # Replace the following with your PostgreSQL connection parameters
+            PSQL_HOST=ec2-3-139-100-35.us-east-2.compute.amazonaws.com
+            PSQL_PORT=5432
+            PSQL_USER=yres
+            PSQL_DB=yres_db
+
+            # Test the PostgreSQL connection
+            if PGPASSWORD=${{ secrets.PG_PASSWORD }} psql -h $PSQL_HOST -p $PSQL_PORT -U $PSQL_USER -d $PSQL_DB -c "SELECT 1"; then
+              echo "PostgreSQL connection successful!"
+            else
+              echo "PostgreSQL connection failed."
+              exit 1
+            fi
   # build-test-deploy:
   #   runs-on: ubuntu-latest
 
